Modelun/config/routes.rb
Rails.application.routes.draw do

    
    
  
  
  devise_for :users
  root to: "static_pages#home"
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  
  
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'user/all' => 'users#index'
  get "notes" => 'static_pages#notes'
  get "crisis_updates" => 'crisis_updates#crisis_updates'
  get "public_resolutions" => 'resolutions#public_resolutions'
  get "private_resolutions" => 'resolutions#private_resolutions'
  get "documents" => 'static_pages#documents'
  get 'static_pages/download' => 'static_pages#download'
  get "resolution_management" => 'resolutions#resolution_management'
  get "resolution_requests" => 'resolution_requests#create'
  get "resolution_signings_create" => 'resolution_signings#create'
  delete 'resolution_signings_destroy' => 'resolution_signings#destroy'
  delete 'resolution_signings' => 'resolution_signings#destroy'
  delete 'directives_tags' => 'directives_tags#destroy'
  delete 'resolution_requests' => 'resolution_requests#destroy'
  delete 'resolution_sponsorships' => 'resolution_sponsorships#destroy'

  resources :users
  resources :crises, :controller => "users", :type => "Crisis"
  resources :delegates, :controller => "users", :type => "Delegate"
  
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  
  resources :directives
  resources :personal_directives,  :controller => "personal_directives"
  resources :resolutions, :controller => "resolutions"
  resources :crisis_updates, :controller => "crisis_updates"
  resources :notes, :controller => "notes", only: [:create, :destroy]
  resources :tags
  resources :directives_tags
  resources :resolution_sponsorships, only: [:create, :destroy]
  resources :resolution_signings, only: [:create, :destroy]
  resources :resolution_requests, only: [:create, :destroy]

  

end

Modelun/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id= "error_explanation">
    <div class= "alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Modelun/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="directives">
    <% @feed_items.each do |item| %>
        <div class = "content">
          <b>Type: </b>
          <%= item.type %>
        </div>
    <% if item.type == "Resolution" %>
        <%= render partial: "resolutions/public_resolutions", locals: {directive: item} %>
    <% elsif item.type == "PersonalDirective" %>
        <%= render partial: "personal_directives/personal_directives", locals: {directive: item} %>
    <% elsif item.type == "CrisisUpdate" %>
        <%= render partial: "crisis_updates/crisis_updates", locals: {directive: item} %>
    <% else %>
        <%= render partial: "directives/notes", locals: {directive: item} %>
    <% end %>
    <% end %>
  </ol>
  <%= will_paginate @feed_items, :param_name => 'page' %>
<% end %>

Modelun/app/views/shared/_new_tag.html.erb
<%= form_for(@tag, html: { multipart: true }) do |f| %>
<div class="field">
    <%= f.text_field :tag %>
    <%= f.submit "new tag", class: "btn btn-primary" %>
</div>

Modelun/app/views/shared/_note_feed.html.erb
<% if @note_feed.any? %>
  <ol class="directives">
    <%= render partial: "directives/notes", collection: @note_feed, as: 'directive' %>
  </ol>
  <%= will_paginate @note_feed, :param_name => 'note_page' %>
<% end %>

Modelun/app/views/shared/_sidebar.html.erb
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <h1><%= current_user.name %></h1>
                </li>
                <li>
                    <span><%= current_user.position %></span>
                </li>
                <li>
                    <span><%= current_user.committee %></span>
                </li>
                <li>
                    <span><%= link_to "view my profile", current_user %></span>
                </li>
                <li>
                    <span><%= link_to "my mailbox", mailbox_inbox_path %></span>
                </li>
                <li>
                    <span><%= link_to "personal directives", personal_directives_path %></span>
                </li>
                <li>
                    <span><%= link_to "committee directives", resolutions_path %></span>
                </li>
                <li>
                    <span><%= link_to "crisis updates", crisis_updates_path %></span>
                </li>
                <li>
                    <span><%= link_to "delegate list", users_path %></span>
                </li>
                <li>
                    <span><%= link_to "crisis notes", notes_path if current_user[:type] == "Crisis"%></span>
                </li>
                <li>
                    <span><%= link_to "filter", 'directives#index' if current_user[:type] == "Crisis" %></span>
                </li>
            </ul>
        </div>

Modelun/app/views/shared/_sponsor.html.erb
<% directive = Directive.find_by(id: directive_id) %>

<%= form_for(directive.sponsorships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :user_id, current_user[:id] %>
  <%= hidden_field_tag :directive_id, directive_id %></div>
  <%= f.submit "Sponsor", class: "btn btn-primary" %>
<% end %>

Modelun/app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= current_user.position %></span>
<span><%= current_user.committee %></span>
<span><%= link_to "My Mailbox", mailbox_inbox_path %>(unread: <%= unread_messages_count %>)</span>
<span><%= link_to "Personal Directives", personal_directives_path %></span>
<span><%= link_to "Public Resolutions", public_resolutions_path %></span>
<span><%= link_to "Private Resolutions", private_resolutions_path if current_user[:type] == "Delegate" %></span>
<span><%= link_to "Crisis Updates", crisis_updates_path %></span>
<span><%= link_to "Delegate List", users_path if current_user.type == "Crisis" %></span>
<span><%= link_to "Information", documents_path %></span>
<span><%= link_to "Crisis Notes", notes_path if current_user[:type] == "Crisis"%></span>
<span><%= link_to "Filter", 'directives#index' if current_user[:type] == "Crisis" %></span>