Modelun/config/routes.rb
Rails.application.routes.draw do

    
    
  
  
  devise_for :users
  root to: "static_pages#home"
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  
  
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'user/all' => 'users#index'
  get "notes" => 'static_pages#notes'
  get "crisis_updates" => 'crisis_updates#crisis_updates'
  get "public_resolutions" => 'resolutions#public_resolutions'
  get "private_resolutions" => 'resolutions#private_resolutions'
  get "documents" => 'static_pages#documents'
  get 'static_pages/download' => 'static_pages#download'
  get "resolution_management" => 'resolutions#resolution_management'
  get "resolution_requests" => 'resolution_requests#create'
  get "resolution_signings_create" => 'resolution_signings#create'
  delete 'resolution_signings_destroy' => 'resolution_signings#destroy'
  delete 'resolution_signings' => 'resolution_signings#destroy'
  delete 'directives_tags' => 'directives_tags#destroy'
  delete 'resolution_requests' => 'resolution_requests#destroy'
  delete 'resolution_sponsorships' => 'resolution_sponsorships#destroy'

  resources :users
  resources :crises, :controller => "users", :type => "Crisis"
  resources :delegates, :controller => "users", :type => "Delegate"
  
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  
  resources :directives
  resources :personal_directives,  :controller => "personal_directives"
  resources :resolutions, :controller => "resolutions"
  resources :crisis_updates, :controller => "crisis_updates"
  resources :notes, :controller => "notes", only: [:create, :destroy]
  resources :tags
  resources :directives_tags
  resources :resolution_sponsorships, only: [:create, :destroy]
  resources :resolution_signings, only: [:create, :destroy]
  resources :resolution_requests, only: [:create, :destroy]

  

end

Modelun/app/models/crisis_update.rb
class CrisisUpdate < Directive
    has_many :update_crises, :foreign_key => :directive_id
    has_many :crises, through: :update_crises
end

Modelun/app/controllers/crisis_updates_controller.rb
class CrisisUpdatesController < DirectivesController
  before_action :authenticate_user!
  def new
    @crisis_update = current_user.crisis_updates.build
  end

  def create
    if current_user.crisis_updates.create(type: params[:crisis_update][:type],
                                          content: params[:crisis_update][:content],
                                          title: params[:crisis_update][:title])
      flash[:success] = "Crisis Updates Created!"
      redirect_to crisis_updates_path
    else
      flash[:error] = "Fail"
      redirect_to request.referrer
    end
  end

  def update
    @directive = Directive.find_by(id: params[:id])
    if @directive.update_attributes(directive_params)
      redirect_to crisis_updates_path
    else
      flash[:error] = "Wrong"
      redirect_to request.referrer
    end
  end

  def crisis_updates
    if user_signed_in?
      if current_user.type == "Delegate"
        @cs_feed = CrisisUpdate.with_committees(current_user.committee).with_public(true).paginate(page: params[:cs_page], per_page: 5)

      elsif current_user[:type] == "Crisis"
        @directive = current_user.crisis_updates.build
        @cs_feed = CrisisUpdate.with_committees(current_user.committee).paginate(page: params[:cs_page], per_page: 5)
      end
    else redirect_to root_url
    end
  end

  private
    def directive_params
      params.require(:crisis_update).permit(:content, :picture, :title, :type, :passed, :public, :status, :editable, :claim, :quality)
    end
end

Modelun/app/views/crisis_updates/_crisis_updates.html.erb
<li id="directive-<%= directive.id %>">
  <% @directive = directive %>

  <span class="content">
    <b>Status: </b>
  <% if current_user[:type] == "Crisis" %>
    <%= link_to "(make public)", directive_path(@directive, :directive => {:public => true}),
                :method => :put,
                :confirm => "Are you sure?" if !directive.public %>
        <%= "Public" if directive.public %>
        <%= "Private" if !directive.public %>
  <span class="content">
    <b>Tags(<%= link_to "new tags",
                        :controller => "tags",
                        :action => "new",
                        :directive_id => directive.id %>):</b>
      <% directive.tags.each do |tag| %>
          #<%= tag.tag %>
      <% end %>
  </span>
  <% end %>
  <b>Posted:</b>
  <%= I18n.l directive.created_at.in_time_zone('Eastern Time (US & Canada)') , :format => :short  %>
  </span>
  <span class= "content">
    <b>Title:</b>
    <%= directive.title %>
  </span>
  <span class="content">
    <b>Content:</b> <br>
    <%= render inline: directive.content %>
    <%= image_tag directive.picture.url if directive.picture? %>
  </span>
  <% if current_user[:type] == "Crisis" %>
  <span class="content">
      <b>Avaliable Actions:</b>
      <%= link_to "edit", 
                        :controller => "directives",
                        :action => "edit",
                        :id => directive.id %>
  </span>
  <% end %>
</li>
<hr style="height: 5px; border: 0px solid black; border-top-width: 1px;" />

Modelun/app/views/crisis_updates/_cs_feed.html.erb
<% if @cs_feed.any? %>
  <ol class="directives">
    <%= render partial: "crisis_updates/crisis_updates", collection: @cs_feed, as: 'directive' %>
  </ol>
  <%= will_paginate @cs_feed, :param_name => 'cs_page' %>
<% end %>

Modelun/app/views/crisis_updates/crisis_updates.html.erb
<% if user_signed_in? && !current_user.nil? %>
    <% provide(:title, current_user.name) %>
    <% @user = current_user %>
    <div class="row">
      <aside class="col-md-3">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>

      </aside>
      <div class="col-md-9">
        <h3>Crisis Updates(<%= @cs_feed.count %>)</h3>
            <%= link_to "new crisis updates", new_crisis_update_path, :target => '_blank' if current_user[:type] == "Crisis"%>
        <% if @cs_feed.any? %>

            <ol class="directives">
          <%= render "cs_feed" %>
        </ol>
      <% end %>
      </div>
    </div>
<% end %>

Modelun/app/views/crisis_updates/new.html.erb
<h2>New Crisis Updates </h2>

<%= form_for(@crisis_update) do |f| %>
    <% if @crisis_update.errors.any? %>
        <div id="error_explanation">
          <h5><%= pluralize(@crisis_update.errors.count, "error") %> prohibited this crisis update from being saved:</h5>

          <ul>
            <% @crisis_update.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :content %>
      <%= f.text_area :content, :class => "tinymce" %>
      <%= tinymce %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>

<% end %>