Modelun/config/routes.rb
Rails.application.routes.draw do

    
    
  
  
  devise_for :users
  root to: "static_pages#home"
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  
  
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'user/all' => 'users#index'
  get "notes" => 'static_pages#notes'
  get "crisis_updates" => 'crisis_updates#crisis_updates'
  get "public_resolutions" => 'resolutions#public_resolutions'
  get "private_resolutions" => 'resolutions#private_resolutions'
  get "documents" => 'static_pages#documents'
  get 'static_pages/download' => 'static_pages#download'
  get "resolution_management" => 'resolutions#resolution_management'
  get "resolution_requests" => 'resolution_requests#create'
  get "resolution_signings_create" => 'resolution_signings#create'
  delete 'resolution_signings_destroy' => 'resolution_signings#destroy'
  delete 'resolution_signings' => 'resolution_signings#destroy'
  delete 'directives_tags' => 'directives_tags#destroy'
  delete 'resolution_requests' => 'resolution_requests#destroy'
  delete 'resolution_sponsorships' => 'resolution_sponsorships#destroy'

  resources :users
  resources :crises, :controller => "users", :type => "Crisis"
  resources :delegates, :controller => "users", :type => "Delegate"
  
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  
  resources :directives
  resources :personal_directives,  :controller => "personal_directives"
  resources :resolutions, :controller => "resolutions"
  resources :crisis_updates, :controller => "crisis_updates"
  resources :notes, :controller => "notes", only: [:create, :destroy]
  resources :tags
  resources :directives_tags
  resources :resolution_sponsorships, only: [:create, :destroy]
  resources :resolution_signings, only: [:create, :destroy]
  resources :resolution_requests, only: [:create, :destroy]

  

end

Modelun/app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end
  
end

Modelun/app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
  
  def send_message_count
    mailbox.sentbox.count(:id, :distinct => true)  
  end
  
end

Modelun/app/views/mailbox/_folder_view.html.erb
<div class="row">
  <div class="spacer"></div>

  <aside class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
    <section class= "user_info">
      <%= render "shared/user_info" %>
    </section>
  </aside>

  <div class="col-md-8">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
    <div class="spacer"></div>
    <div class="panel panel-default">
      <div class="panel-body">

        <% if is_conversation %>
          <%= render 'conversations/form' %>
        <% else %>
          <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
      </div>
    </div>
  </div>
</div>

Modelun/app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%= unread_messages_count %></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>
      <span class="label label-warning pull-right"><%= send_message_count %></span>
        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

Modelun/app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

Modelun/app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

Modelun/app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>