Modelun/config/routes.rb
Rails.application.routes.draw do

    
    
  
  
  devise_for :users
  root to: "static_pages#home"
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  
  
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'user/all' => 'users#index'
  get "notes" => 'static_pages#notes'
  get "crisis_updates" => 'crisis_updates#crisis_updates'
  get "public_resolutions" => 'resolutions#public_resolutions'
  get "private_resolutions" => 'resolutions#private_resolutions'
  get "documents" => 'static_pages#documents'
  get 'static_pages/download' => 'static_pages#download'
  get "resolution_management" => 'resolutions#resolution_management'
  get "resolution_requests" => 'resolution_requests#create'
  get "resolution_signings_create" => 'resolution_signings#create'
  delete 'resolution_signings_destroy' => 'resolution_signings#destroy'
  delete 'resolution_signings' => 'resolution_signings#destroy'
  delete 'directives_tags' => 'directives_tags#destroy'
  delete 'resolution_requests' => 'resolution_requests#destroy'
  delete 'resolution_sponsorships' => 'resolution_sponsorships#destroy'

  resources :users
  resources :crises, :controller => "users", :type => "Crisis"
  resources :delegates, :controller => "users", :type => "Delegate"
  
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  
  resources :directives
  resources :personal_directives,  :controller => "personal_directives"
  resources :resolutions, :controller => "resolutions"
  resources :crisis_updates, :controller => "crisis_updates"
  resources :notes, :controller => "notes", only: [:create, :destroy]
  resources :tags
  resources :directives_tags
  resources :resolution_sponsorships, only: [:create, :destroy]
  resources :resolution_signings, only: [:create, :destroy]
  resources :resolution_requests, only: [:create, :destroy]

  

end

Modelun/app/models/resolution.rb
class Resolution < Directive
    has_many :sponsorships, class_name: "ResolutionSponsorship",
                            foreign_key: "directive_id"
                            
    has_many :sponsors, through: :sponsorships, 
                        class_name: "Delegate",
                        source: :delegate
                        
    
    has_many :signatures, class_name: "ResolutionSigning",
                            foreign_key: "directive_id"
                            
    has_many :signers, through: :signatures, 
                        class_name: "Delegate",
                        source: :delegate
                        
    has_many :creations, class_name: "ResolutionCreation",
                            foreign_key: "directive_id"

    has_many :creators, through: :creations, 
                        class_name: "Delegate",
                        source: :delegate

    has_many :requests, class_name: "ResolutionRequest",
             foreign_key: "directive_id"

    has_many :requestors, through: :requests,
             class_name: "Delegate",
             source: :delegate
                        
end

Modelun/app/controllers/resolutions_controller.rb
class ResolutionsController < DirectivesController
  before_action :authenticate_user!
  def new
    @resolution = current_user.created_resolutions.build
  end

  def create
    resolution = current_user.created_resolutions.build(type: params[:resolution][:type],
                                                       content: params[:resolution][:content],
                                                       title: params[:resolution][:title])
    if resolution.save
      flash[:success] = "Resolutions/Committee Directives Created!"
      resolution.creations.create(user_id: current_user[:id])

      if params[:resolution][:sponsors] != nil
        params[:resolution][:sponsors].each do |sponsor|
          resolution.sponsorships.create(user_id: sponsor)
        end
      end

      if params[:resolution][:signers] != nil
        params[:resolution][:signers].each do |signer|
          resolution.signatures.create(user_id: signer)
        end
      end
      redirect_to private_resolutions_path
    else
      flash[:error] = "Fail"
      @resolution = resolution
      render "resolutions/new"
    end


  end

  def update
    @directive = Directive.find_by(id: params[:id])
    if @directive.update_attributes(directive_params)
      redirect_to root_url
    else
      flash[:error] = "Wrong"
    end
  end

  def public_resolutions

    committee_users = "SELECT users.id FROM users WHERE users.committee = :committee"
    relevant_directives = "SELECT directive_id FROM directives_users WHERE user_id in (#{committee_users})"
    relevant_tags = "SELECT tag_id FROM directives_tags WHERE directive_id in (#{relevant_directives})"
    tags = Tag.where("tags.id in (#{relevant_tags})",committee: current_user.committee)

    comments = Resolution.with_comments
    @filterrific = initialize_filterrific(
        Directive,
        params[:filterrific],
        select_options: {
            with_tag_name: tags.options_for_select,
            with_user: Delegate.where(committee: current_user.committee).options_for_select,
            with_directive_status: ["On The Floor", "Draft", "Passed!", "Failed!"]
        }
    ) or return
    filter_result = @filterrific.find

    if user_signed_in?
      @user = current_user
      if current_user[:type] == "Delegate"
        resolutions_ids = "SELECT directive_id FROM directives_users
                                  WHERE user_id = :user_id"
        sql_result = Resolution.with_committees(current_user.committee).where("public = 't'")
        @resolution = current_user.created_resolutions.build

      elsif current_user[:type] == "Crisis"
        user_ids = "SELECT users.id FROM users WHERE committee = :committee"
        committee_directive_ids = "SELECT directive_id FROM directives_users
                        WHERE user_id IN (#{user_ids}) AND type IN ('ResolutionSponsorship',
                        'ResolutionSigning', 'ResolutionCreation')"
        sql_result = Resolution.with_committees(current_user.committee).where("directives.id IN (#{committee_directive_ids}) AND public = 't'",
                                    committee: current_user[:committee])

      end

      if params[:reply]
        @rs_feed = ((filter_result & sql_result) - comments).paginate(page: params[:rs_page], per_page: 5)
      else
        @rs_feed = (filter_result & sql_result).paginate(page: params[:rs_page], per_page: 5)
      end

    else redirect_to root_url
    end
  end

  def private_resolutions
    if user_signed_in?
      @user = current_user
      if current_user[:type] == "Delegate"
        resolutions_ids = "SELECT directive_id FROM directives_users
                                  WHERE user_id = :user_id AND type != 'ResolutionRequest'"
        @rs_feed = Resolution.with_committees(current_user.committee).distinct.where("directives.id IN (#{resolutions_ids} and public = 'f')",
                                    user_id: current_user[:id]).paginate(page: params[:rs_page], per_page: 5)
        @resolution = current_user.created_resolutions.build
      end
    else redirect_to root_url
    end
  end

  def resolution_management
    @sponsorship = current_user.sponsorships.new
    @signature = current_user.signatures.new
  end


  private
      def directive_params
          params.require(:resolution).permit(:content, :picture, :title, :type, :editable, :passed, :status, :public)
      end
end

Modelun/app/views/resolutions/_private_resolutions.html.erb
<li id="directive-<%= directive.id %>">
  <span class = "content">
    <% if directive.creators.include?(current_user) %>


            <b>Status(<%= link_to "make public", directive_path(directive, :directive => {:public => true}),
                                 :method => :put,
                                 :confirm => "Are you sure?" %>):</b>
            <% if !directive[:public] %>
                Private
            <% else %>
              <%= directive[:status] %>
    <% end %>
    <% end %>
    <br>
    <b>Creators:</b>
    <% directive.creators.each do |creator| %>
    <%= creator.position %>,
    <% end %>
    <br>

    <% unless directive.creators.include?(current_user) %>
  <span id="content">
    <b>Sponsors</b>:<% if directive.sponsors.include?(current_user) %>(<%= link_to "unsponsor", resolution_sponsorships_path(:directive_id => directive.id), :method => :delete  %>)
    <% end %>

        <% directive.sponsors.each do |sponsor| %>
          <%= sponsor.position %>
        <% end %>
        <br>
  </span>
    <% end %>
  <% if directive.creators.include?(current_user) %>
  <span class="content">
    <b>Sponsorship Requests: </b>
    <% directive.requestors.each do |sponsor| %>
          <% if !directive.sponsors.include?(sponsor) %>
            <%= sponsor.position %> ,
          <% end %>
      <% end %>
  <% end %>
  </span>
    <% unless directive.creators.include?(current_user) %>
      <span id="content">
      <b>Signers</b>:(<% if directive.signers.include?(current_user) && current_user.type == "Delegate" %>
              <%= link_to "unsign", resolution_signings_destroy_path(:directive_id => directive.id), :method => :delete %>
      <% elsif !directive.signers.include?(current_user) && current_user.type == "Delegate" %>
              <%= link_to "sign", resolution_signings_create_path(:html_options => {:method => :post}, :directive_id => directive.id)  %>

      <% end %> ):

        <% directive.signers.each do |sponsor| %>
              <%= sponsor.position %>,
          <% end %>
        </span>
      <% end %>
  </span>
  <span class= "content">
    <b>Posted: </b>
    <%= I18n.l directive.created_at.in_time_zone('Eastern Time (US & Canada)') , :format => :short  %>
  </span>
  <span class= "content">
    <b>Title:</b>
    <%= directive.title %>
  </span>
  <span class="content">
    <b>Content:</b> <br>
    <%= render inline: directive.content %>
    <%= image_tag directive.picture.url if directive.picture? %>
  </span>
  <span class="content">
    <b>Avaliable Actions:</b>
    <% if directive.creators.include?(current_user) or current_user.admin == true  %>

      <%= link_to "delete", directive, method: :delete,
                  data: { confirm: "You sure?" } %>,
        <%= link_to "edit",
                    {:controller => "directives",
                    :action => "edit",
                    :id => directive.id},
                    :target => "_blank"
                    %>,
    <% end %>
    <% if directive.sponsors.include?(current_user) or directive.creators.include?(current_user) %>
    <%= link_to "friendly amendaments",
                {:controller => "comments",
                :action => "new",
                :directive_id => directive.id,
                :function => "Friendly Amendaments"},
                :target => "_blank" %>,
    <% end %>
    <%= link_to "unfriendly amendaments",
                {:controller => "comments",
                :action => "new",
                :directive_id => directive.id,
                :function => "Unfriendly Amendaments"},
                :target => "_blank"%>,
    <% if directive.creators.include?(current_user) %>
    <%= link_to "resolution management",
                {:controller => "resolutions",
                :action => "resolution_management",
                :directive_id => directive.id},
                :target => "_blank"
                %>

    <% end %>
  </span>

  <% if current_user[:type] == "Crisis" %>
    <span>
        <% directive.tags.each do |tag| %>
            #<%= tag.tag %>
        <% end %>
    </span>

    <span>
      <%= link_to "new tags",
                  {:controller => "tags",
                  :action => "new",
                  :directive_id => directive.id},
                  :target => "_blank" %>
    </span>
  <% end %>
  <span class="content">
  <b>Amendaments:</b><br><br>
  <%= comments_tree_for directive.comments.hash_tree %>
  </span>
</li>
<hr style="height: 5px; border: 0px solid black; border-top-width: 1px;" />

Modelun/app/views/resolutions/_public_resolutions.html.erb
<li id="directive-<%= directive.id %>">
  <span class = "content">
    <% @directive = directive %>

    <b>Status<%= link_to "(make private)", directive_path(@directive, :directive => {:public => false}),
                         :method => :put,
                         :confirm => "Are you sure?" if directive.creators.include?(current_user) %>:</b>
    <%= directive[:status] %>
    <% if current_user.type == "Crisis" %> <br>
      <b>Change Status:</b>
      <%= link_to "draft,", directive_path(@directive, :directive => {:status => "Draft"}), :method => :put %>
      <%= link_to "on floor,", directive_path(@directive, :directive => {:status => "On The Floor"}), :method => :put %>
      <%= link_to "pass,", directive_path(@directive, :directive => {:status => "Passed!"}), :method => :put %>
      <%= link_to "fail,", directive_path(@directive, :directive => {:status => "Failed!"}), :method => :put %>
    <% end %>
    <br>
    <b>Creators:</b>
    <% directive.creators.each do |creator| %>
      <%= creator.position %>
    <% end %>
    <br>

    <% unless directive.creators.include?(current_user) %>
        <div id="content">
          <b>Sponsors</b><% if directive.requestors.include?(current_user) && !directive.sponsors.include?(current_user) && current_user.type == "Delegate" %>
              (<%= link_to "unrequest", resolution_requests_path(:directive_id => directive.id), :method => :delete %>)
          <% elsif !directive.requestors.include?(current_user) && !directive.sponsors.include?(current_user) && current_user.type == "Delegate" %>
              (<%= link_to "request", resolution_requests_path(:html_options => {:method => :post}, :directive_id => directive.id)  %>)
          <% elsif directive.sponsors.include?(current_user) && current_user.type == "Delegate" %>
              (<%= link_to "unsponsor", resolution_sponsorships_path(:directive_id => directive.id), :method => :delete  %>)
          <% end %>:
          <% directive.sponsors.each do |sponsor| %>
              <%= sponsor.position %>,
          <% end %>
          <br>
        </div>
    <% end %>

    <% if directive.creators.include?(current_user) %>
      <span class="content">
        <b>Sponsorship Requests: </b>
        <% directive.requestors.each do |sponsor| %>
              <% if !directive.sponsors.include?(sponsor) %>
                <%= sponsor.position %>,
              <% end %>
          <% end %>
      </span>
    <% end %>

    <% unless directive.creators.include?(current_user) %>
      <span id="content">
          <b>Signers</b>:<% if directive.signers.include?(current_user) && current_user.type == "Delegate" %>
              (<%= link_to "unsign", resolution_signings_destroy_path(:directive_id => directive.id), :method => :delete %>)
      <% elsif !directive.signers.include?(current_user) && current_user.type == "Delegate" %>
              (<%= link_to "sign", resolution_signings_create_path(:html_options => {:method => :post}, :directive_id => directive.id)  %>)

      <% end %>:

          <% directive.signers.each do |sponsor| %>
              <%= sponsor.position %>,
          <% end %>
        </span>
      <% end %>


      <span class="content">
        <b>Posted: </b>
        <%= I18n.l directive.created_at.in_time_zone('Eastern Time (US & Canada)'), :format => :short %>
      </span>



  <% if current_user[:type] == "Crisis" %>
    <span class="content">
      <b>Tags: </b>
      <% directive.tags.each do |tag| %>
            #<%= tag.tag %>
      <% end %>
      <%= link_to "new tags",
                  {:controller => "tags",
                  :action => "new",
                  :directive_id => directive.id},
                  :target => '_blank'%>
    </span>
  <% end %>
  <span class="content">
    <b>Title:</b>
    <%= directive.title %>
  </span>



  <span class="content">
    <b>Content:</b> <br>
    <%= render inline: directive.content %>
    <%= image_tag directive.picture.url if directive.picture? %>
  </span>

  <% if current_user.type == "Delegate" %>
  <span class="content">
    <b>Avaliable Actions:</b>

    <% if directive.creators.include?(current_user) or current_user.admin == true %>
      <%= link_to "delete", directive, method: :delete,
                  data: {confirm: "You sure?"} %>,
        <%= link_to "edit",
                    {:controller => "directives",
                    :action => "edit",
                    :id => directive.id},
                    :target => '_blank'%>,
    <% end %>
    <% if directive.sponsors.include?(current_user) or directive.creators.include?(current_user) %>
    <%= link_to "friendly amendaments",
                {:controller => "comments",
                :action => "new",
                :directive_id => directive.id,
                :function => "Friendly Amendaments"},
                :target => '_blank'%>,
    <% end %>

    <%= link_to "unfriendly amendaments",
                {:controller => "comments",
                :action => "new",
                :directive_id => directive.id,
                :function => "Unfriendly Amendaments"},
                :target => '_blank'%>,

    <% if directive.creators.include?(current_user) %>
    <%= link_to "resolution management",
                {:controller => "resolutions",
                :action => "resolution_management",
                :directive_id => directive.id},
                :target => '_blank'%>
    <% end %>

  </span>


  <% end %>

  <span class="content">
  <b>Amendaments:</b><br><br>
    <%= comments_tree_for directive.comments.hash_tree %>
  </span>
  </span>
</li>
<hr style="height: 5px; border: 0px solid black; border-top-width: 1px;"/>

Modelun/app/views/resolutions/_rs_feed.html.erb
<% if @rs_feed.any? %>

  <ol class="directives">
    <%= render partial: "private_resolutions", collection: @rs_feed, as: 'directive' %>
  </ol>

  <%= will_paginate @rs_feed, :param_name => 'rs_page' %>

<% end %>

Modelun/app/views/resolutions/new.html.erb
<h2>New Resolutions</h2>

<%= form_for(@resolution) do |f| %>
<% if @resolution.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@resolution.errors.count, "error") %> prohibited this resolution from being saved:</h2>

    <ul>
        <% @resolution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%= hidden_field_tag :creator, current_user[:id] %>


<div class="form-group">
  <%= f.label :sponsors %>
  <%= f.select(:sponsors, Delegate.where(committee: current_user.committee).where.not(id: current_user.id).collect {|p| [ p.position, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
</div>

<div class="form-group">
  <%= f.label :signers %>
  <%= f.select(:signers, Delegate.where(committee: current_user.committee).where.not(id: current_user.id).collect {|p| [ p.position, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
</div>

<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :content %>
  <%= f.text_area :content, :class => "tinymce" %>
  <%= tinymce %>
</div>

<%= f.submit class: 'btn btn-primary' %>
<% end %>

Modelun/app/views/resolutions/private_resolutions.html.erb
<% if user_signed_in? && !@user.nil? %>
    <% provide(:title, @user.position) %>
    <% @user = current_user %>
    <div class="row">
      <aside class="col-md-3">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <% if current_user[:type] == "Delegate" %>
        <% end %>
      </aside>
      <div class="col-md-9">
        <% if !@rs_feed.nil? %>
            <h3>Private Resolutions(<%= @rs_feed.count %>)</h3>
            <%= link_to "new resolutions", new_resolution_path, :target => '_blank' %>
            <ol class="directives">
              <% if @rs_feed.any? %>
                  <ol class="directives">
                    <%= render partial: "private_resolutions", collection: @rs_feed, as: 'directive' %>
                  </ol>
                  <%= will_paginate @rs_feed, :param_name => 'rs_page' %>
              <% end %>
            </ol>
        <% end %>
      </div>
    </div>
<% end %>

Modelun/app/views/resolutions/public_resolutions.html.erb
<% if user_signed_in? %>
    <% provide(:title, current_user.position) %>
    <div class="row">
      <aside class="col-md-3">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>

        <%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>
            <div>
              Search
              <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
              <%= f.text_field(
                      :search_query,
                  ) %>
            </div>
            <% if current_user[:type] == "Crisis" %>
            <div>
              Tags
              <%= f.select(
                      :with_tag_name,
                      @filterrific.select_options[:with_tag_name],
                      { include_hidden: false, include_blank: '- Any -' }, multiple:true, class: "chosen-select form-control"
                  ) %>
            </div>
            <div>
              User
              <%= f.select(
                      :with_user,
                      @filterrific.select_options[:with_user],
                      { include_hidden: false, include_blank: '- Any -' }, multiple:true, class: "chosen-select form-control"
                  ) %>
            </div>
            <% end %>
            <div>
              Directive Status
              <%= f.select(
                      :with_directive_status,
                      @filterrific.select_options[:with_directive_status],
                      { include_hidden: false, include_blank: '- Any -' }, multiple:true, class: "chosen-select form-control"
                  ) %>
            </div>
            <%= f.submit "submit" %>

            <% end %>

      </aside>
      <div class="col-md-9">
        <h3>Public Resolutions(<%= @rs_feed.count %>)</h3>
        <%= link_to "new resolutions", new_resolution_path , :target => '_blank' if current_user.type == "Delegate" %>
        <% if @rs_feed.any? %>
        <ol class="directives">
          <ol class="directives">
            <%= render partial: "public_resolutions", collection: @rs_feed, as: 'directive' %>
          </ol>
          <%= will_paginate @rs_feed, :param_name => 'rs_page' %>
        </ol>
      <% end %>
      </div>
    </div>
<% end %>

Modelun/app/views/resolutions/resolution_management.html.erb
<% directive = Directive.find_by(id: params[:directive_id]) %>
<h1>Current Resolution</h1>
<div class="well">
    <p>
    Below display all existing Sponsors and Signers of your resolution. At this page,
    you can remove current sponsors/signatures or add new sponsors/signatures. 
    </p>
    <h5>
      <b>Sponsorship Requests: </b>
      <% directive.requestors.each do |sponsor| %>
          <% if !directive.sponsors.include?(sponsor) %>
            <%= sponsor.position %> ,
          <% end %>
      <% end %>
    </h5>
    <h5>
        <b>Sponsors: </b>
        <% directive.sponsors.each do |sponsor| %>
            <%= sponsor.position %> ,
        <% end %>
    </h5>
    <h5>
        <b>Signers: </b>
        <% directive.signers.each do |signer| %>
            <%= signer.position %> ,
        <% end %>
    </h5>    
    
</div>
<h4>Resolution Content</h4>

<span>
    <b>Title:</b> <%= directive.title %> <br>
    <b>Content:</b> <br> <%= render inline: directive.content %> <br>
</span>

<h4>Add New Sponsors</h4>

<%= form_for(@sponsorship) do |f| %>
  <% non_sponsors = [] %> 
	<% Delegate.where(committee: current_user.committee).all.each do |s| %>
	    <% if !directive.sponsors.include?(s) && !directive.signers.include?(s) && 
	    !directive.creators.include?(s) %>
	    <% non_sponsors << [s.position, s.id] %>
	    <% end %>
	    <% end %>
  <%= hidden_field_tag :directive_id, directive.id %>
  <%= f.select :user_id, options_for_select(non_sponsors) %>
  <%= f.submit "Add Sponsor", class: 'btn btn-primary' %>
  
<% end %>

<h4>Remove Existing Signers</h4>

<%= form_for(@signature, :html => { :method => :delete }) do |f| %>
  <% signers= [] %>
	<% directive.signers.all.each do |s| %>
	  <% signers << [s.position, s.id] %>
	<% end %>
  <%= hidden_field_tag :directive_id, directive.id %>
  <%= f.select :user_id, options_for_select(signers) %>
  <%= f.submit "Delete Signers", class: 'btn btn-primary' %>
  
<% end %>


<h4>Add New Signers</h4>

<%= form_for(@signature) do |f| %>
  <% non_signers = [] %> 
	<% Delegate.where(committee: current_user.committee).all.each do |s| %>
	    <% if !directive.sponsors.include?(s) && !directive.signers.include?(s) && 
	    !directive.creators.include?(s) %>
	    <% non_signers << [s.position, s.id] %>
	    <% end %>
	    <% end %>
  <%= hidden_field_tag :directive_id, directive.id %>
  <%= f.select :user_id, options_for_select(non_signers) %>
  <%= f.submit "Add Signer", class: 'btn btn-primary' %>
  
<% end %>